[package]
name = "justlaunch"
version = "0.0.0"
authors = ["S Stewart <iamtheworst@programmer.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.1.0-beta"